//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoteles.ReservaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/ReservaHoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_habitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_hotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_reservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_contactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_entradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_reservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_salidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telef_contactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_habitacion {
            get {
                return this.cod_habitacionField;
            }
            set {
                if ((this.cod_habitacionField.Equals(value) != true)) {
                    this.cod_habitacionField = value;
                    this.RaisePropertyChanged("cod_habitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_hotel {
            get {
                return this.cod_hotelField;
            }
            set {
                if ((this.cod_hotelField.Equals(value) != true)) {
                    this.cod_hotelField = value;
                    this.RaisePropertyChanged("cod_hotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_reserva {
            get {
                return this.cod_reservaField;
            }
            set {
                if ((this.cod_reservaField.Equals(value) != true)) {
                    this.cod_reservaField = value;
                    this.RaisePropertyChanged("cod_reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.comentariosField, value) != true)) {
                    this.comentariosField = value;
                    this.RaisePropertyChanged("comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_contacto {
            get {
                return this.doc_contactoField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_contactoField, value) != true)) {
                    this.doc_contactoField = value;
                    this.RaisePropertyChanged("doc_contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_entrada {
            get {
                return this.fecha_entradaField;
            }
            set {
                if ((this.fecha_entradaField.Equals(value) != true)) {
                    this.fecha_entradaField = value;
                    this.RaisePropertyChanged("fecha_entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_reserva {
            get {
                return this.fecha_reservaField;
            }
            set {
                if ((this.fecha_reservaField.Equals(value) != true)) {
                    this.fecha_reservaField = value;
                    this.RaisePropertyChanged("fecha_reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_salida {
            get {
                return this.fecha_salidaField;
            }
            set {
                if ((this.fecha_salidaField.Equals(value) != true)) {
                    this.fecha_salidaField = value;
                    this.RaisePropertyChanged("fecha_salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telef_contacto {
            get {
                return this.telef_contactoField;
            }
            set {
                if ((object.ReferenceEquals(this.telef_contactoField, value) != true)) {
                    this.telef_contactoField = value;
                    this.RaisePropertyChanged("telef_contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documentoField, value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservaServicio.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/RegistrarReserva", ReplyAction="http://tempuri.org/IReservaService/RegistrarReservaResponse")]
        int RegistrarReserva(Hoteles.ReservaServicio.Reserva ReservaACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/RegistrarReserva", ReplyAction="http://tempuri.org/IReservaService/RegistrarReservaResponse")]
        System.Threading.Tasks.Task<int> RegistrarReservaAsync(Hoteles.ReservaServicio.Reserva ReservaACrear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : Hoteles.ReservaServicio.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<Hoteles.ReservaServicio.IReservaService>, Hoteles.ReservaServicio.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarReserva(Hoteles.ReservaServicio.Reserva ReservaACrear) {
            return base.Channel.RegistrarReserva(ReservaACrear);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarReservaAsync(Hoteles.ReservaServicio.Reserva ReservaACrear) {
            return base.Channel.RegistrarReservaAsync(ReservaACrear);
        }
    }
}
